[2025-04-12 16:42:08,527] - INFO - common - YAML loaded successfully from: 'config\config.yaml'
[2025-04-12 16:42:08,527] - INFO - common - YAML loaded successfully from: 'config\params.yaml'
[2025-04-12 16:42:08,527] - INFO - common - YAML loaded successfully from: 'config\schema.yaml'
[2025-04-12 16:42:08,527] - INFO - common - Created directory at: 'artifacts'
[2025-04-12 16:42:08,527] - INFO - common - Created directory at: 'artifacts/mongodb'
[2025-04-12 16:42:08,911] - INFO - common - CSV converted and saved to: 'artifacts/mongodb/input_data_json.json'
[2025-04-12 16:42:09,798] - INFO - mongo_handler - Attempting to connect to MongoDB...
[2025-04-12 16:42:09,888] - INFO - mongo_handler - MongoDB connection established.
[2025-04-12 16:42:09,888] - INFO - mongo_handler - Using database: 'network_security_db'
[2025-04-12 16:42:09,888] - INFO - mongo_handler - Using collection: 'phishing_records'
[2025-04-12 16:42:09,900] - INFO - mongo_handler - Inserting 11055 record(s) into MongoDB...
[2025-04-12 16:42:21,320] - INFO - mongo_handler - 11055 record(s) inserted successfully into MongoDB.
[2025-04-12 16:42:40,539] - INFO - common - Created directory at: 'artifacts/data_ingestion'
[2025-04-12 16:42:40,539] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\data_ingestion.py], line [25], message: ['DataIngestionConfig' object has no attribute 'feature_store_file_path']
